FROM fprime_base:latest

# 기본 시스템 패키지 설치
RUN apt-get update && apt-get install -y --no-install-recommends \
    protobuf-compiler \
    libprotobuf-dev \
    pkg-config \
    autoconf \
    libtool \
    ninja-build \
    liblzma-dev \
    libz-dev \
  && rm -rf /var/lib/apt/lists/*

RUN pip3 install --no-cache-dir cmake --upgrade
--init --recursive # Moved earlier

# 작업 디렉토리 다시 설정
WORKDIR /workspace/Efficient-Fuzzer

# libFuzzer 진입점 스크립트 복사 (COPY 명령어 대신 클론된 저장소에서 복사)
RUN cp /workspace/Efficient-Fuzzer/src/protobuf-mutator/entrypoint-protobuf_mutator.sh /usr/local/bin/entrypoint.sh

# python-protobuf 설치 (이미 설치되어 있으면 생략 가능)
RUN pip install "protobuf<=3.20.3"

# proto → python 코드 생성
WORKDIR /workspace/Efficient-Fuzzer/src/protobuf-mutator
RUN protoc --python_out=. cmd_dispatcher_fuzz_input.proto

# seed 자동 생성 스크립트 복사 및 실행
COPY make_seeds.py .
RUN python3 make_seeds.py

# libprotobuf-mutator 설치
WORKDIR /workspace
RUN git clone https://github.com/google/libprotobuf-mutator.git && \
    cd libprotobuf-mutator && \
    mkdir build && cd build && \
    cmake .. -GNinja \
      -DCMAKE_C_COMPILER=clang \
      -DCMAKE_CXX_COMPILER=clang++ \
      -DCMAKE_BUILD_TYPE=Release \
      -DLIB_PROTO_MUTATOR_DOWNLOAD_PROTOBUF=OFF \
      -DBUILD_SHARED_LIBS=OFF && \
    ninja -v && \
    ninja -v install

    
# 줄 끝 문자 변환
RUN dos2unix /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh


# 컨테이너 실행 시 libFuzzer 컴파일 및 실행
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
