FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

# 기본 시스템 패키지 설치
RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    build-essential \
    clang \
    clang-14 \
    llvm-14 \
    llvm-14-dev \
    libclang-14-dev \
    g++ \
    python3 \
    python3-pip \
    python3-venv \
    make \
    curl \
    dos2unix \
    protobuf-compiler \
    libprotobuf-dev \
    pkg-config \
    autoconf \
    libtool \
    ninja-build \
    liblzma-dev \
    libz-dev \
  && rm -rf /var/lib/apt/lists/*

# fprime 빌드 도구 설치
RUN pip3 install -U fprime-tools fprime-gds
# pip를 사용하여 최신 CMake 설치
RUN pip3 install --no-cache-dir cmake --upgrade

# 작업 디렉토리 설정
WORKDIR /workspace

# fprime 프로젝트 클론 및 설정 (특정 브랜치 지정)
RUN git clone -b Week13/temp https://github.com/seunghyeoks/Efficient-Fuzzer.git

# 프로젝트 디렉토리로 이동
WORKDIR /workspace/Efficient-Fuzzer

# submodule 초기화 및 업데이트
RUN git submodule init && \
    git submodule update --recursive

# fprime 도구 추가 설치
RUN pip install -r "/workspace/Efficient-Fuzzer/src/fprime/requirements.txt"

# fprime 디렉토리로 이동하여 해당 컨텍스트에서 서브모듈을 확실히 업데이트합니다.
WORKDIR /workspace/Efficient-Fuzzer/src/fprime
RUN git submodule init && git submodule update --init --recursive


# CmdDispatcher 테스트 하네스 생성 (UT 전용)
WORKDIR /workspace/Efficient-Fuzzer/src/fprime/Svc/CmdDispatcher
RUN fprime-util generate --ut && fprime-util build --ut


WORKDIR /workspace/Efficient-Fuzzer/src/fprime

RUN fprime-util generate && fprime-util build
RUN git submodule update --init --recursive # Moved earlier

# 작업 디렉토리 다시 설정
WORKDIR /workspace/Efficient-Fuzzer

# libFuzzer 진입점 스크립트 복사 (COPY 명령어 대신 클론된 저장소에서 복사)
RUN cp /workspace/Efficient-Fuzzer/src/libFuzzer/entrypoint-libFuzzer.sh /usr/local/bin/entrypoint.sh

# 줄 끝 문자 변환
RUN dos2unix /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh


# libprotobuf-mutator 설치
WORKDIR /workspace
RUN git clone https://github.com/google/libprotobuf-mutator.git && \
    cd libprotobuf-mutator && \
    mkdir build && cd build && \
    cmake .. -GNinja -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_BUILD_TYPE=Release -DLIB_PROTO_MUTATOR_DOWNLOAD_PROTOBUF=OFF && \
    ninja -v && \
    ninja -v install






# 컨테이너 실행 시 libFuzzer 컴파일 및 실행
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
