services:
  libfuzzer:
    build:
      context: .
      dockerfile: libFuzzer2/Dockerfile.libfuzzer
    container_name: fprime_libfuzzer
    privileged: true
    volumes:
      - ../..:/workspace/local-code
      - libfuzzer-findings:/workspace/Efficient-Fuzzer/build/libfuzzer/findings
    tty: true
    stdin_open: true
    # AFL++ 및 Boofuzz 컨테이너는 나중에 추가

volumes:
  libfuzzer-findings:
    # 퍼저가 발견한 크래시, 타임아웃 등의 결과를 저장할 볼륨 