services:
  gramatron:
    build:
      context: ./gramatron
      dockerfile: Dockerfile.gramatron
    container_name: fprime_gramatron
    privileged: true
    volumes:
      - ../..:/workspace/local-code
    tty: true
    stdin_open: true