services:

  protobuf_mutator:
    build:
      context: ./protobuf-mutator
      dockerfile: Dockerfile.protobuf_mutator
    container_name: fprime_protobuf_mutator
    privileged: true
    volumes:
      - ../..:/workspace/local-code
    tty: true
    stdin_open: true